### ISSUE TITLE
Publish with Fable support

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fsprojects/MarkerClustering#2]
The library can be published to support being consumed by Fable projects easily since it doesn't have any special dependencies and it would be nice to work with from the [Feliz.PigeonMaps](https://zaid-ajaj.github.io/Feliz/#/Ecosystem/PigeonMaps) project which doesn't include any clustering support ATM.  

You only need to include these lines in the project definition and publish a new version
```xml
    <ItemGroup>
        <Content Include="*.fsproj; *.fs; *.js;" PackagePath="fable\" />
    </ItemGroup>
```
This way, you will include the source files of the project (i.e. the `GeoClustering.fs` file) into a directory called `fable` in the published package as required by Fable

**Comment by forki** [comment]
PR more than welcome.
